version: '3.8'

services:
  restaurant-app:
    build: .
    container_name: restaurant_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=production

